### ISSUE TITLE
dependencies in emconf and composer

### ISSUE THREAD

**Issue by madaxel** [lochmueller/focuspoint#80] opened 2020-09-10 09:20 UTC
Hi @lochmueller,

https://github.com/lochmueller/focuspoint/blob/38c7678a6800766231eb88923bee7f796efe2dfe/ext_emconf.php#L27 the dependency seems to be >= 4.0.0 
https://github.com/lochmueller/focuspoint/blob/38c7678a6800766231eb88923bee7f796efe2dfe/composer.json#L19
it is 4.0.x|| 5.0.x || 6.0.x
see https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
this is inconsistent. Just noticed while migrating a project to composer

**Comment by lochmueller** [comment] 2020-09-10 09:42
Hey @madaxel 
Thank you for reporting. The problem is already fixed in the current master (and next release).
I will close this issue...
Regards,
Tim

**Closed by lochmueller** 2020-09-10 09:42 UTC
